package xyz.easiersaid.twr.protocol

fun instructionTiming(instruction: AtcInstruction): InstructionTiming? = when (instruction) {
    is ConditionalClearance -> instructionTiming(instruction.instruction)

    is TaxiTo,
    is CrossRunway,
    is BacktrackRunway -> InstructionTiming.SEQUENTIAL

    is SetSquawk,
    is ConfirmSquawk,
    is SquawkIdent,
    is SquawkStandby,
    is SquawkNormal,
    is StopSquawk,
    is SetPressure,
    is ClimbTo,
    is DescendTo,
    is ExpediteClimb,
    is ExpediteDescend,
    is MaintainLevel,
    is StopClimbAt,
    is StopDescentAt,
    is MaintainAtOrAbove,
    is MaintainAtOrBelow,
    is AfterPassingLevelClimbTo,
    is AfterPassingLevelDescendTo,
    is MaintainAltitudeUntilEstablished,
    is MaintainSpeed,
    is ReduceSpeedTo,
    is IncreaseSpeedTo,
    is MinimumCleanSpeed,
    is ResumeNormalSpeed,
    is ContactFrequency,
    is MonitorFrequency -> InstructionTiming.IMMEDIATE

    is HoldPosition,
    is HoldShortOf,
    is LineUpAndWait,
    is Orbit,
    is ExtendDownwind,
    is HoldAt -> InstructionTiming.PERSISTENT

    // Standalone instructions — not used inside compound clearances
    is StartupApproved,
    is PushbackApproved,
    is PushbackFace,
    is TaxiViaRunway,
    is AirTaxiTo,
    is VacateRunway,
    is TaxiIntoHoldingBay,
    is TaxiWithCaution,
    is ExpediteTaxi,
    is ReduceTaxiSpeed,
    is GiveWayToTraffic,
    is ClearedForTakeoff,
    is ClearedToLand,
    is ClearedTouchAndGo,
    is ClearedLowApproach,
    is GoAround,
    is HoldPositionCancelTakeoff,
    is StopImmediately,
    is TakeoffImmediatelyOrVacateRunway,
    is TakeoffImmediatelyOrHoldShort,
    is AfterLandingVacateVia,
    is ClearedTo,
    is ProceedDirect,
    is ResumeOwnNavigation,
    is RouteAsFiled,
    is JoinAirway,
    is RejoinSidAt,
    is LeaveHoldProceedDirect,
    is WhenAbleProceedDirect,
    is FlyHeading,
    is TurnHeading,
    is TurnByDegrees,
    is ContinuePresentHeading,
    is StopTurn,
    is InterceptLocaliser,
    is ClearedApproach,
    is ContinueApproach,
    is JoinCircuit,
    is MakeShortApproach,
    is MakeLongApproach,
    is TurnBase,
    is MakeAnotherCircuit,
    is CommenceApproachAt,
    is ReportWhen,
    is ReportTrafficInSight,
    is FollowTraffic,
    is NumberInSequence,
    is MaintainVisualSeparation,
    is DivertTo,
    is ClearedToEnterControlZone,
    is RemainOutsideControlledAirspace -> null
}

fun instructionDomain(instruction: AtcInstruction): ClearanceDomain? = when (instruction) {
    is ConditionalClearance -> instructionDomain(instruction.instruction)

    is StartupApproved,
    is PushbackApproved,
    is PushbackFace,
    is TaxiTo,
    is TaxiViaRunway,
    is AirTaxiTo,
    is HoldPosition,
    is HoldShortOf,
    is CrossRunway,
    is BacktrackRunway,
    is VacateRunway,
    is TaxiIntoHoldingBay,
    is TaxiWithCaution,
    is ExpediteTaxi,
    is ReduceTaxiSpeed,
    is GiveWayToTraffic -> ClearanceDomain.GROUND

    is LineUpAndWait,
    is ClearedForTakeoff,
    is ClearedToLand,
    is ClearedTouchAndGo,
    is ClearedLowApproach,
    is GoAround,
    is HoldPositionCancelTakeoff,
    is StopImmediately,
    is TakeoffImmediatelyOrVacateRunway,
    is TakeoffImmediatelyOrHoldShort,
    is AfterLandingVacateVia,
    is JoinCircuit,
    is ExtendDownwind,
    is TurnBase,
    is Orbit,
    is MakeAnotherCircuit,
    is MakeShortApproach,
    is MakeLongApproach,
    is FollowTraffic,
    is NumberInSequence,
    is MaintainVisualSeparation -> ClearanceDomain.RUNWAY

    is ClearedTo,
    is ProceedDirect,
    is ResumeOwnNavigation,
    is RouteAsFiled,
    is JoinAirway,
    is RejoinSidAt,
    is HoldAt,
    is LeaveHoldProceedDirect,
    is WhenAbleProceedDirect,
    is ClearedApproach,
    is ContinueApproach,
    is CommenceApproachAt,
    is FlyHeading,
    is TurnHeading,
    is TurnByDegrees,
    is ContinuePresentHeading,
    is StopTurn,
    is InterceptLocaliser,
    is RemainOutsideControlledAirspace,
    is ClearedToEnterControlZone -> ClearanceDomain.ROUTE

    is ClimbTo,
    is DescendTo,
    is ExpediteClimb,
    is ExpediteDescend,
    is MaintainLevel,
    is StopClimbAt,
    is StopDescentAt,
    is MaintainAtOrAbove,
    is MaintainAtOrBelow,
    is AfterPassingLevelClimbTo,
    is AfterPassingLevelDescendTo,
    is MaintainAltitudeUntilEstablished -> ClearanceDomain.LEVEL

    is MaintainSpeed,
    is ReduceSpeedTo,
    is IncreaseSpeedTo,
    is MinimumCleanSpeed,
    is ResumeNormalSpeed -> ClearanceDomain.SPEED

    is SetSquawk,
    is ConfirmSquawk,
    is SquawkIdent,
    is SquawkStandby,
    is SquawkNormal,
    is StopSquawk -> ClearanceDomain.SQUAWK

    is ContactFrequency,
    is MonitorFrequency -> ClearanceDomain.FREQUENCY

    // Instructions with no specific domain
    is SetPressure,
    is ReportWhen,
    is ReportTrafficInSight,
    is DivertTo -> null
}

fun instructionSupersedesIn(instruction: AtcInstruction): Set<ClearanceDomain> =
    when (instruction) {
        is ConditionalClearance -> instructionSupersedesIn(instruction.instruction)
        is GoAround -> setOf(ClearanceDomain.RUNWAY, ClearanceDomain.ROUTE, ClearanceDomain.LEVEL)
        is ClearedApproach -> setOf(ClearanceDomain.ROUTE, ClearanceDomain.LEVEL)
        else -> buildSet { instructionDomain(instruction)?.let(::add) }
    }

fun instructionCompletionCategory(instruction: AtcInstruction): CompletionCategory? = when (instruction) {
    is ConditionalClearance -> instructionCompletionCategory(instruction.instruction)

    is TaxiTo,
    is CrossRunway,
    is BacktrackRunway,
    is ClearedForTakeoff,
    is ClearedToLand,
    is ClearedTouchAndGo,
    is ClearedLowApproach,
    is AfterLandingVacateVia,
    is ClearedTo,
    is ProceedDirect,
    is JoinAirway,
    is RejoinSidAt,
    is LeaveHoldProceedDirect,
    is WhenAbleProceedDirect,
    is ClimbTo,
    is DescendTo,
    is ExpediteClimb,
    is ExpediteDescend,
    is MaintainLevel,
    is StopClimbAt,
    is StopDescentAt,
    is MaintainAtOrAbove,
    is MaintainAtOrBelow,
    is AfterPassingLevelClimbTo,
    is AfterPassingLevelDescendTo,
    is MaintainAltitudeUntilEstablished,
    is MaintainSpeed,
    is ReduceSpeedTo,
    is IncreaseSpeedTo,
    is ConfirmSquawk,
    is SquawkIdent,
    is SquawkStandby,
    is SquawkNormal,
    is StopSquawk,
    is JoinCircuit -> CompletionCategory.SELF_COMPLETING

    is SetSquawk,
    is SetPressure,
    is ResumeOwnNavigation,
    is RouteAsFiled,
    is MinimumCleanSpeed,
    is ResumeNormalSpeed -> CompletionCategory.ON_ACTIVATION

    is ContactFrequency,
    is MonitorFrequency -> CompletionCategory.EXTERNAL_EVENT

    is HoldPosition,
    is HoldShortOf,
    is LineUpAndWait,
    is Orbit,
    is ExtendDownwind,
    is HoldAt -> CompletionCategory.PERSISTENT

    // Instructions with no modelled completion
    is StartupApproved,
    is PushbackApproved,
    is PushbackFace,
    is TaxiViaRunway,
    is AirTaxiTo,
    is VacateRunway,
    is TaxiIntoHoldingBay,
    is TaxiWithCaution,
    is ExpediteTaxi,
    is ReduceTaxiSpeed,
    is GiveWayToTraffic,
    is GoAround,
    is HoldPositionCancelTakeoff,
    is StopImmediately,
    is TakeoffImmediatelyOrVacateRunway,
    is TakeoffImmediatelyOrHoldShort,
    is FlyHeading,
    is TurnHeading,
    is TurnByDegrees,
    is ContinuePresentHeading,
    is StopTurn,
    is InterceptLocaliser,
    is ClearedApproach,
    is ContinueApproach,
    is MakeShortApproach,
    is MakeLongApproach,
    is TurnBase,
    is MakeAnotherCircuit,
    is CommenceApproachAt,
    is ReportWhen,
    is ReportTrafficInSight,
    is FollowTraffic,
    is NumberInSequence,
    is MaintainVisualSeparation,
    is DivertTo,
    is ClearedToEnterControlZone,
    is RemainOutsideControlledAirspace -> null
}

fun instructionMayBeConditional(instruction: AtcInstruction): Boolean = when (instruction) {
    is PushbackApproved,
    is TaxiTo,
    is TaxiViaRunway,
    is AirTaxiTo,
    is HoldShortOf,
    is CrossRunway,
    is BacktrackRunway,
    is LineUpAndWait -> true

    is ConditionalClearance,
    is StartupApproved,
    is PushbackFace,
    is HoldPosition,
    is VacateRunway,
    is TaxiIntoHoldingBay,
    is TaxiWithCaution,
    is ExpediteTaxi,
    is ReduceTaxiSpeed,
    is GiveWayToTraffic,
    is ClearedForTakeoff,
    is ClearedToLand,
    is ClearedTouchAndGo,
    is ClearedLowApproach,
    is GoAround,
    is HoldPositionCancelTakeoff,
    is StopImmediately,
    is TakeoffImmediatelyOrVacateRunway,
    is TakeoffImmediatelyOrHoldShort,
    is AfterLandingVacateVia,
    is ClearedTo,
    is ProceedDirect,
    is ResumeOwnNavigation,
    is RouteAsFiled,
    is JoinAirway,
    is RejoinSidAt,
    is HoldAt,
    is LeaveHoldProceedDirect,
    is WhenAbleProceedDirect,
    is FlyHeading,
    is TurnHeading,
    is TurnByDegrees,
    is ContinuePresentHeading,
    is StopTurn,
    is InterceptLocaliser,
    is ClimbTo,
    is DescendTo,
    is ExpediteClimb,
    is ExpediteDescend,
    is MaintainLevel,
    is StopClimbAt,
    is StopDescentAt,
    is MaintainAtOrAbove,
    is MaintainAtOrBelow,
    is AfterPassingLevelClimbTo,
    is AfterPassingLevelDescendTo,
    is MaintainAltitudeUntilEstablished,
    is MaintainSpeed,
    is ReduceSpeedTo,
    is IncreaseSpeedTo,
    is MinimumCleanSpeed,
    is ResumeNormalSpeed,
    is ClearedApproach,
    is ContinueApproach,
    is JoinCircuit,
    is MakeShortApproach,
    is MakeLongApproach,
    is ExtendDownwind,
    is TurnBase,
    is Orbit,
    is MakeAnotherCircuit,
    is CommenceApproachAt,
    is ReportWhen,
    is ReportTrafficInSight,
    is FollowTraffic,
    is NumberInSequence,
    is MaintainVisualSeparation,
    is ContactFrequency,
    is MonitorFrequency,
    is SetSquawk,
    is ConfirmSquawk,
    is SquawkIdent,
    is SquawkStandby,
    is SquawkNormal,
    is StopSquawk,
    is SetPressure,
    is DivertTo,
    is ClearedToEnterControlZone,
    is RemainOutsideControlledAirspace -> false
}
