package xyz.easiersaid.twr.pilot

import xyz.easiersaid.twr.core.world.AviationWorld
import xyz.easiersaid.twr.core.world.WorldIndex
import xyz.easiersaid.twr.protocol.AerodromeId
import xyz.easiersaid.twr.protocol.AircraftId
import xyz.easiersaid.twr.protocol.Atis
import xyz.easiersaid.twr.protocol.Callsign
import xyz.easiersaid.twr.protocol.CurrentInformationIs
import xyz.easiersaid.twr.protocol.InitialContact
import xyz.easiersaid.twr.protocol.PointId
import xyz.easiersaid.twr.protocol.RoleName
import xyz.easiersaid.twr.protocol.RunwayConfiguration
import xyz.easiersaid.twr.protocol.RunwayId
import xyz.easiersaid.twr.protocol.SimTime
import xyz.easiersaid.twr.protocol.Wind
import kotlin.test.Test
import kotlin.test.assertEquals

/**
 * Pass 15 (D-AUDIT.8 closure) — pilot-side ATIS letter flow:
 * lazy-read at first contact, plus per-leaf processControllerResponse
 * arm for `CurrentInformationIs`.
 *
 * Doctrine: ICAO Annex 11 §4.3 (ATIS service); §4.3.6 (advisory
 * transmission, no readback obligation).
 */
class AtisLetterPropagationSpec {

    private val LOWG = AerodromeId("LOWG")
    private val ac = AircraftId("OE-ABC")
    private val now0 = SimTime.ofMillis(0)

    private fun atis(letter: Char) = Atis(
        letter = letter,
        aerodrome = LOWG,
        configuration = RunwayConfiguration(
            arrivals = listOf(RunwayId("16C")),
            departures = listOf(RunwayId("16C")),
        ),
        wind = Wind.unsafe(160, 8),
        qnh = null,
        visibility = null,
        generatedAt = now0,
    )

    private fun aircraft(): AircraftState = AircraftState(
        id = ac,
        callsign = Callsign("OEABC"),
        position = xyz.easiersaid.twr.core.world.Position(0.0, 0.0),
        positionPoint = PointId("HOLD"),
        phase = PilotPhase.HoldingShort,
    )

    /**
     * Build a mission whose active step is `CALL_INBOUND`. The
     * `arrivalJoinTask()` opens with `CALL_INBOUND`; an Arrival goal
     * spawned at AtStand reaches it after the ground steps are
     * marked complete (which they aren't, by default). Simplest
     * route: construct the task tree directly with CALL_INBOUND
     * active.
     */
    private fun missionAtCallInbound(): PilotMission = PilotMission(
        goal = HighLevelGoal.Arrival(),
        root = CompoundTask(
            name = TaskName.ArrivalJoin,
            children = listOf(
                PrimitiveTask(MissionStep.CALL_INBOUND, CompletionMode.REPORTED),
            ),
        ),
        stepEnteredAt = now0,
    )

    @Test
    fun `pilot InitialContact carries current ATIS letter at first contact per Annex 11 sec4dot3dot6`() {
        // Pilot's mission has CALL_INBOUND active. The PilotInput carries
        // the published ATIS via `atisByAerodrome`. The transmission
        // generated by `pilotCognitiveDecide` for CALL_INBOUND embeds
        // the letter in `InitialContact.atisCode`.
        val mission = missionAtCallInbound().copy(
            // Set pendingInitialContactRole so the InitialContact targets a
            // sensible role.
            pendingInitialContactRole = arrow.core.Some(RoleName.TOWER),
        )
        val decision = pilotCognitiveDecide(
            aircraft = aircraft().copy(pilotMission = mission),
            mission = mission,
            worldIndex = WorldIndex(),
            now = now0,
            atisByAerodrome = mapOf(LOWG to atis('A')),
        )
        val initialContact = decision.transmissions
            .filterIsInstance<InitialContact>()
            .firstOrNull()
        assertEquals(
            'A',
            initialContact?.atisCode,
            "Annex 11 §4.3.6: pilot embeds the current ATIS letter in first contact. " +
                "Got transmissions=${decision.transmissions}",
        )
    }

    @Test
    fun `pilot processControllerResponse(CurrentInformationIs) is silent acknowledgement per Annex 11 sec4dot3dot6`() {
        // Annex 11 §4.3.6: advisory transmission, no readback obligation.
        val mission = missionAtCallInbound()
        val response = CurrentInformationIs(target = ac, letter = 'B')
        val reaction = processControllerResponse(response, mission)
        assertEquals(mission, reaction.mission, "advisory must not mutate mission")
        assertEquals(
            arrow.core.None,
            reaction.transmission,
            "Annex 11 §4.3.6: pilot acknowledges silently, no readback transmission",
        )
    }
}
